# Generated by Django 4.1 on 2022-09-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_auto_20210720_1249"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
